name: shared
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  logger: ^2.6.1
  image_picker: ^1.1.2
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1