name: ads
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core
  shared:
    path: ../../shared
  iap:
    path: ../iap

  flutter_riverpod: ^2.6.1
  google_mobile_ads: ^6.0.0
  app_tracking_transparency: ^2.0.6+1

dev_dependencies:
  flutter_lints: ^6.0.0
