name: ads
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  core:
    git:
      url: https://github.com/3unbeom/mono.git
      path: packages/core
  shared:
    git:
      url: https://github.com/3unbeom/mono.git
      path: packages/shared
  iap:
    git:
      url: https://github.com/3unbeom/mono.git
      path: packages/features/iap

  flutter_riverpod: ^2.6.1
  google_mobile_ads: ^6.0.0
  app_tracking_transparency: ^2.0.6+1

dev_dependencies:
  flutter_lints: ^6.0.0
