name: iap
description: In-App Purchase feature package
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # In-App Purchase with RevenueCat
  purchases_flutter: ^9.1.0
  
  # Data models
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  
  # Local packages
  core:
    path: ../../core
  shared:
    path: ../../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0