name: profile
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core
  
  shared:
    path: ../../shared

  flutter_riverpod: ^2.6.1
  supabase_flutter: ^2.9.1
  image_picker: ^1.1.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0
